name: SEtup node and install dependencies
description: "set up Node.js, caches dependencies, and installs them"
runs:
  using: composite
  steps:
    - name: Setup Node Js
      uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Print Node version
      run: node -v
      shell: bash
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm -y install
      shell: bash